### ISSUE TITLE
Detailed status and tray menu status do not match

### ISSUE THREAD

**Issue by gorkem** [code-ready/tray-macos#31]
For some reason detailed status can recognize that my cluster is running while the rest of the tray does not get updated with this information. I am guessing this is also the reason why web console and oc login menu items are not enabled.

![Screen Shot 2020-04-25 at 3 43 32 PM](https://user-images.githubusercontent.com/82738/80289495-b8eb3100-870c-11ea-8e45-43b92cf92418.png)

**Comment by anjannath** [comment]
>  am guessing this is also the reason why web console and oc login menu items are not enabled.

Yes, since we don't periodically update the menus based on the cluster status, they remain disabled.. and maybe the start had some errors so it still shows the status as unknown.

I am thinking to update the menu items and the status text, by polling for the cluster status. this is what i did for the windows tray and it shows the status correctly, with a small delay after you click on the tray icon since it needs to fetch the status from the daemon.

**Comment by gorkem** [comment]
At least the detailed status should update the menu status.
